<?php
session_start();
unset($_SESSION['EUSERS_ID']);
unset($_SESSION['EUSERS_NAME']);
unset($_SESSION['edit_password']);
unset($_SESSION['remove_password']);
unset($_SESSION['order_series']);
unset($_SESSION['series_start']);
unset($_SESSION['CURRENT_ORDER']);
unset($_SESSION['I_TYPE']);
unset($_SESSION['EFYEAR_ID']);
unset($_SESSION['TLIST']);
unset($_SESSION['TUID']);
unset($_SESSION['db']);
unset($_SESSION['GSTSTATE']);
unset($_SESSION['user_privilage']);
unset($_SESSION['TCompanyCode']);
unset($_SESSION['TBranchCode']);
unset($_SESSION['TCompanyName']);
unset($_SESSION['TCompanyType']);
unset($_SESSION['OUT']);
unset($_SESSION['maindb']);
unset($_SESSION['first']);
session_destroy();
date_default_timezone_set("Asia/Kolkata");
//$dir = '../bup/';
//$a=array();
//$a=glob($dir.'*.sql');
//$b=$a[0];
//unlink($b);
//include('backup.php');
?>
<script>
window.location.href='../index.php?ms=2';
</script>
